In [18]:
import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('./'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


./iris.data.csv
./iris.ipynb
./.ipynb_checkpoints\iris-checkpoint.ipynb


In [19]:
train_df = pd.read_csv('./iris.data.csv', header = None)
train_df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [20]:
train_df.shape

(150, 5)

In [21]:
X = train_df.drop([4], axis=1)
y = train_df[4]

In [22]:
class_labels = list(set(y))
print(class_labels)

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']


In [23]:
def encode_labels(samples):
    res = []
    for sample in samples:
        for id, x in enumerate(class_labels):
            if x == sample:
                res.append(id)
                break
    return res
y = encode_labels(y)
y[:5]

[0, 0, 0, 0, 0]

In [24]:
X.shape

(150, 4)

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                   random_state=69) 
y_train[:5]

[0, 0, 0, 2, 2]

In [26]:
from sklearn import metrics
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

In [27]:
y_train=tf.keras.utils.to_categorical(y_train,3)
y_test=tf.keras.utils.to_categorical(y_test,3)

In [28]:
input_size = 4
output_size = 3

model = tf.keras.Sequential([
                            tf.keras.layers.InputLayer(input_shape=(4)),
                            tf.keras.layers.Dense(4, activation='relu'),
                            tf.keras.layers.Dense(4, activation='relu'),
                            tf.keras.layers.Dense(3, activation='relu'),   
                            tf.keras.layers.Dense(output_size, activation='softmax')   
                            ])

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 4)                 20        
                                                                 
 dense_5 (Dense)             (None, 4)                 20        
                                                                 
 dense_6 (Dense)             (None, 3)                 15        
                                                                 
 dense_7 (Dense)             (None, 3)                 12        
                                                                 
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [31]:
NUM_EPOCHS = 70

model.fit(X_train,y_train, epochs = NUM_EPOCHS, validation_data=(X_test,y_test), verbose=2)

Epoch 1/70
4/4 - 1s - loss: 1.1010 - accuracy: 0.2250 - val_loss: 1.1000 - val_accuracy: 0.2667 - 649ms/epoch - 162ms/step
Epoch 2/70
4/4 - 0s - loss: 1.0993 - accuracy: 0.3000 - val_loss: 1.0994 - val_accuracy: 0.2667 - 33ms/epoch - 8ms/step
Epoch 3/70
4/4 - 0s - loss: 1.0988 - accuracy: 0.3417 - val_loss: 1.0992 - val_accuracy: 0.2667 - 32ms/epoch - 8ms/step
Epoch 4/70
4/4 - 0s - loss: 1.0984 - accuracy: 0.3417 - val_loss: 1.0992 - val_accuracy: 0.2667 - 33ms/epoch - 8ms/step
Epoch 5/70
4/4 - 0s - loss: 1.0982 - accuracy: 0.3500 - val_loss: 1.0990 - val_accuracy: 0.3000 - 32ms/epoch - 8ms/step
Epoch 6/70
4/4 - 0s - loss: 1.0981 - accuracy: 0.3500 - val_loss: 1.0987 - val_accuracy: 0.3000 - 33ms/epoch - 8ms/step
Epoch 7/70
4/4 - 0s - loss: 1.0978 - accuracy: 0.3667 - val_loss: 1.0983 - val_accuracy: 0.3000 - 31ms/epoch - 8ms/step
Epoch 8/70
4/4 - 0s - loss: 1.0974 - accuracy: 0.3667 - val_loss: 1.0978 - val_accuracy: 0.3000 - 32ms/epoch - 8ms/step
Epoch 9/70
4/4 - 0s - loss: 1.0962 - 

Epoch 69/70
4/4 - 0s - loss: 0.6549 - accuracy: 0.6750 - val_loss: 0.6679 - val_accuracy: 0.6000 - 30ms/epoch - 8ms/step
Epoch 70/70
4/4 - 0s - loss: 0.6519 - accuracy: 0.6750 - val_loss: 0.6650 - val_accuracy: 0.6000 - 33ms/epoch - 8ms/step


In [32]:
y_predict = model.predict(X_test)

In [34]:
y_pred = []
for val in y_predict:
    y_pred.append(np.argmax(val))
# print(y_pred)    
#convert 0 1 to 1 and 1 0 as 0
accuracy = metrics.accuracy_score(np.argmax(y_test,axis = 1) ,y_pred)
recall = metrics.recall_score(np.argmax(y_test,axis = 1) ,y_pred,average='macro')
precision = metrics.precision_score(np.argmax(y_test,axis = 1) ,y_pred,average='macro')
f1_score = metrics.f1_score(np.argmax(y_test,axis = 1) ,y_pred,average='macro')
cm = metrics.confusion_matrix(np.argmax(y_test,axis = 1) ,y_pred)
print(cm)
print("Accuracy:",accuracy)
print("F1 score:",f1_score)
print("Recall:",recall)
print("Precision:",precision)

[[10  0  0]
 [ 0  8  0]
 [ 0 12  0]]
Accuracy: 0.6
F1 score: 0.5238095238095238
Recall: 0.6666666666666666
Precision: 0.4666666666666666


c:\users\mange\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [39]:
print(y_pred)

[0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0]
